// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD844gXpnwqzMbBfIZzpS_OuOzrddgZ-to',
    appId: '1:436089112714:web:1c1b720f5a791805d78573',
    messagingSenderId: '436089112714',
    projectId: 'expansetracker-f1d11',
    authDomain: 'expansetracker-f1d11.firebaseapp.com',
    storageBucket: 'expansetracker-f1d11.firebasestorage.app',
    measurementId: 'G-RZQR3DL0XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrIa3-tFx7Ir8vNp1wZ2rqvHnXIbMlLc',
    appId: '1:436089112714:android:9c8aa797e6ee257ad78573',
    messagingSenderId: '436089112714',
    projectId: 'expansetracker-f1d11',
    storageBucket: 'expansetracker-f1d11.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfll1aFAgiuc9mRuI877-H260tI1UwJY',
    appId: '1:436089112714:ios:308ca8af6b44f529d78573',
    messagingSenderId: '436089112714',
    projectId: 'expansetracker-f1d11',
    storageBucket: 'expansetracker-f1d11.firebasestorage.app',
    iosBundleId: 'com.example.expanseTrackerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgfll1aFAgiuc9mRuI877-H260tI1UwJY',
    appId: '1:436089112714:ios:308ca8af6b44f529d78573',
    messagingSenderId: '436089112714',
    projectId: 'expansetracker-f1d11',
    storageBucket: 'expansetracker-f1d11.firebasestorage.app',
    iosBundleId: 'com.example.expanseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD844gXpnwqzMbBfIZzpS_OuOzrddgZ-to',
    appId: '1:436089112714:web:062ebbdb8b195264d78573',
    messagingSenderId: '436089112714',
    projectId: 'expansetracker-f1d11',
    authDomain: 'expansetracker-f1d11.firebaseapp.com',
    storageBucket: 'expansetracker-f1d11.firebasestorage.app',
    measurementId: 'G-YK0KN10NB4',
  );
}
